"""Seed realistic dummy work permits + activities (SAP-style printouts).

Creates the demo permit set you'd expect on a real Unit-10 board:
exchanger cleaning, pump maintenance, CBD deblinding, blinding jobs on an
exchanger / a pump / a column, two adjacent exchangers (one open, one
closed), plus routine ACTIVITIES with SOP references (probe replacements,
pump changeover, exchanger handover). Everything is logged into the SIMOPS
jobs log (making /api/simops/combinations and /api/handover demoable
immediately) and printed to sample_permits/*.txt in SAP work-order style.

All data is FICTIONAL and marked as generated. Deterministic - no LLM.

Usage: python seed_permits.py [--fresh]   (--fresh clears the jobs log first)
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import simops
from config import APP_DIR

OUT_DIR = APP_DIR / "sample_permits"
TODAY = time.strftime("%Y-%m-%d")

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def sap_print(p: dict, order_no: int, notif_no: int) -> str:
    """SAP PM work-order style permit printout (text, monospace)."""
    status = "PERMIT-OPEN " if p["status"] == "open" else "PERMIT-CLOSED"
    sys_status = "REL  PRT  GMPS" if p["status"] == "open" else "TECO CNF  PRT "
    ops = "\n".join(f"  {i:04d}  {op}" for i, op in
                    zip(range(10, 10 + 10 * len(p["operations"]), 10), p["operations"]))
    gas = ("  Gas Test Req : YES   LEL: ____ %   O2: ____ %   H2S: ____ ppm"
           if p.get("gas_test") else
           "  Gas Test Req : NO")
    return f"""------------------------------------------------------------------------
 SAP R/3          WORK ORDER / PTW PRINT                    PAGE 1 OF 1
------------------------------------------------------------------------
 Order        : {order_no:012d}          Order Type : PM02
 Notification : {notif_no:010d}            Priority   : {p['priority']}
 Sys. Status  : {sys_status}         User Status: {status}
 Func. Loc.   : IN01-U10-{p['equipment_tag'].replace('-', '')}
 Equipment    : {p['equipment_tag']:<12} {p['equipment_desc']}
 Planner Grp  : U10    Main WorkCtr : {p['work_center']}
 Bas. Start   : {p['validity']['from']}      Bas. Finish: {p['validity']['to']}
 Permit Type  : {p['permit_type'].upper().replace('_', ' ')}{' / ' + p['job_kind'].upper() if p.get('job_kind') else ''}
 SOP Ref.     : {p.get('sop_ref') or '-'}
------------------------------------------------------------------------
 Description  : {p['job_description']}
 Operations   :
{ops}
------------------------------------------------------------------------
{gas}
  Isolations   : {'; '.join(p['isolations']) or '-'}
  PPE          : {', '.join(p['ppe'])}
------------------------------------------------------------------------
  Issuer (Prod): __________   Receiver (Maint): __________
  Area In-chg  : __________   Safety Officer  : __________
  *** FICTIONAL DEMO PERMIT - generated by incidentwise seed_permits.py ***
------------------------------------------------------------------------"""


def _permit(no: str, ptype: str, tag: str, desc_eq: str, job: str, wc: str,
            ops: list[str], iso: list[str], ppe: list[str], status: str,
            gas: bool, kind: str = "", sop: str = "",
            start_h: int = 8, end_h: int = 18) -> dict:
    return {"permit_no": no, "permit_type": ptype, "unit": "Unit-10 (CDU)",
            "equipment_tag": tag, "equipment_desc": desc_eq,
            "job_description": job, "work_center": wc, "operations": ops,
            "isolations": iso, "ppe": ppe, "status": status,
            "gas_test": gas, "job_kind": kind, "sop_ref": sop, "priority": "2-High",
            "validity": {"from": f"{TODAY} {start_h:02d}:00",
                         "to": f"{TODAY} {end_h:02d}:00"},
            "generated_dummy": True}


PERMITS = [
    _permit("CW-2026-1101", "cold_work", "10-E-109A", "Crude preheat exchanger shell A",
            "Bundle pulling and hydrojetting of 10-E-109A; shells B/C/D remain in service",
            "MECH-U10",
            ["Confirm isolation & spading per blind list BL-109A",
             "Drain & depressurize shell side to CBD",
             "Pull bundle with extractor; shift to cleaning bay",
             "Hydrojet tubes; inspect baffles; box up"],
            ["Spades at shell in/out", "Channel head drains open to CBD"],
            ["helmet", "goggles", "hydrojet suit"], "open", True,
            kind="exchanger cleaning", sop="SOP-MNT-018"),
    _permit("CW-2026-1102", "cold_work", "10-P-103A", "Hot crude pump A",
            "Mechanical seal replacement of 10-P-103A; B pump running with auto-start defeated",
            "ROT-U10",
            ["LOTO on motor; verify zero energy",
             "Close suction/discharge; drain casing to LPD-7",
             "Replace seal per OEM plan; align; trial run"],
            ["Electrical LOTO", "Suction & discharge valves closed + tagged"],
            ["helmet", "face shield", "nitrile gloves"], "open", True,
            kind="pump maintenance", sop="SOP-ROT-009"),
    _permit("CW-2026-1095", "line_breaking", "10-CBD-01", "Closed blowdown drum",
            "Deblinding of CBD header after E-109A box-up; restore normal lineup",
            "MECH-U10",
            ["Verify header depressurized; gas test at flange",
             "Remove blind B-CBD-04; fit new gasket; torque per spec",
             "Leak test at operating pressure"],
            ["Header isolated at battery limit"],
            ["helmet", "goggles", "H2S escape set"], "closed", True,
            kind="deblinding", sop="SOP-MNT-012"),
    _permit("CW-2026-1103", "line_breaking", "10-E-110", "Kero/crude exchanger",
            "Blinding of 10-E-110 shell side for upcoming inspection",
            "MECH-U10",
            ["Depressurize & drain shell side", "Insert blind at inlet/outlet per BL-110",
             "Record blinds in blind register"],
            ["Shell side drained to CBD"],
            ["helmet", "goggles", "gloves"], "open", True,
            kind="blinding", sop="SOP-MNT-012"),
    _permit("CW-2026-1088", "line_breaking", "10-P-104", "Naphtha reflux pump",
            "Blinding of 10-P-104 suction/discharge for seal pot modification",
            "MECH-U10",
            ["Drain casing; verify LEL zero", "Insert blinds; update register"],
            ["Electrical LOTO", "Suction/discharge closed"],
            ["helmet", "goggles", "FR suit"], "closed", True,
            kind="blinding", sop="SOP-MNT-012"),
    _permit("CS-2026-0231", "confined_space", "10-C-201", "Crude column",
            "Blinding of all column nozzles per blind list BL-201 ahead of internal inspection entry",
            "MECH-U10",
            ["Steam-out complete; cool down", "Blind all nozzles per BL-201 (34 blinds)",
             "Ventilate; gas test; entry board up"],
            ["All nozzles blinded per BL-201", "Energy isolation certificate"],
            ["helmet", "BA set standby", "tripod & winch"], "open", True,
            kind="blinding", sop="SOP-CSE-003"),
    _permit("HW-2026-0412", "hot_work", "10-E-111", "VR/crude exchanger",
            "Weld repair of leaking shell nozzle on 10-E-111 (10-E-112 adjacent, IN SERVICE)",
            "MECH-U10",
            ["Erect fire blankets toward 10-E-112", "Continuous gas monitoring",
             "Weld per WPS-88; fire watch 30 min post-work"],
            ["Shell side spaded", "Fire water hose charged at location"],
            ["FR suit", "welding shield", "fire watch"], "open", True,
            kind="weld repair", sop="SOP-HW-001"),
    _permit("CW-2026-1079", "cold_work", "10-E-112", "VR/crude exchanger",
            "Insulation restoration on 10-E-112 after previous inspection",
            "CIVIL-U10",
            ["Scaffold check tag verify", "Re-clad insulation panels"],
            [], ["helmet", "gloves"], "closed", False,
            kind="insulation", sop=""),
]

ACTIVITIES = [
    _permit("AC-2026-0501", "cold_work", "10-K-101", "Off-gas compressor",
            "Replacement of vibration probe VE-101X on 10-K-101 (machine running - online job)",
            "INST-U10", ["Bypass VMS trip per MOC-T-112", "Replace probe; verify gap voltage",
                         "Normalize trip; log in VMS register"],
            ["Trip bypass authorized & time-limited"],
            ["helmet", "ear muffs"], "open", False,
            kind="vibration probe replacement", sop="SOP-ROT-014", start_h=10, end_h=13),
    _permit("AC-2026-0502", "cold_work", "10-K-101", "Off-gas compressor",
            "Bearing temperature probe (TE-101B) replacement on 10-K-101 NDE bearing",
            "INST-U10", ["Bypass bearing temp trip per MOC-T-113", "Replace RTD; verify reading",
                         "Normalize trip"],
            ["Trip bypass authorized"],
            ["helmet", "ear muffs"], "open", False,
            kind="bearing temperature probe replacement", sop="SOP-ROT-015",
            start_h=11, end_h=14),
    _permit("AC-2026-0503", "cold_work", "10-P-103A", "Hot crude pump pair",
            "Planned changeover 10-P-103A -> 10-P-103B for A-pump seal job",
            "PROD-U10", ["Warm up B pump per SOP", "Swap per changeover checklist",
                         "Confirm A isolated & handed to maintenance"],
            [], ["helmet"], "open", False,
            kind="pump changeover", sop="SOP-OPS-022", start_h=7, end_h=8),
    _permit("AC-2026-0504", "cold_work", "10-E-109A", "Crude preheat exchanger shell A",
            "Handover of 10-E-109A from production to maintenance after draining/steaming",
            "PROD-U10", ["Verify drained, depressurized, steamed", "Blind list BL-109A verified jointly",
                         "Sign equipment handover certificate"],
            ["Per blind list BL-109A"], ["helmet", "goggles"], "open", False,
            kind="exchanger handover", sop="SOP-MNT-031", start_h=7, end_h=9),
]


def main() -> int:
    if "--fresh" in sys.argv and simops.JOBS_PATH.exists():
        simops.JOBS_PATH.unlink()
        print("Cleared jobs log.")
    OUT_DIR.mkdir(exist_ok=True)
    order, notif = 4712300, 10234500
    for p in PERMITS + ACTIVITIES:
        order += 1
        notif += 1
        txt = sap_print(p, order, notif)
        path = OUT_DIR / f"{p['permit_no']}_{p['equipment_tag']}.txt"
        path.write_text(txt, encoding="utf-8")
        job = simops.log_job(p)
        print(f"{p['status']:>6}  {p['permit_no']}  {p['equipment_tag']:<10} "
              f"{p.get('job_kind',''):<32} -> {path.name}  (job {job['job_id']})")
    print(f"\n{len(PERMITS) + len(ACTIVITIES)} permits/activities seeded -> {OUT_DIR}")
    print("Try now:  GET /api/simops/combinations   and   POST /api/handover")
    print(json.dumps({"open": sum(1 for p in PERMITS + ACTIVITIES if p['status'] == 'open'),
                      "closed": sum(1 for p in PERMITS + ACTIVITIES if p['status'] == 'closed')}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
